"""add_service_package_price_to_booking

Revision ID: a8f57b3e4e2a
Revises: 42d5e3e5312d
Create Date: 2026-07-17 03:33:06.177102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8f57b3e4e2a'
down_revision: Union[str, Sequence[str], None] = '42d5e3e5312d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('service_package_price_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'service_package_prices', ['service_package_price_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'service_package_price_id')
    # ### end Alembic commands ###
